name: Release

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4
              name: Check out Git repository

            - uses: actions/setup-node@v1
              name: Set up Node.js
              with:
                  node-version: 20

            - run: npm i -g pnpm
              name: Install pnpm

            - run: pnpm install
              name: Install dependencies

            - run: pnpm lint
              name: Run lint

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{github.actor}}
                  password: ${{secrets.GITHUB_TOKEN}}

            - name: Build the Docker image
              run: docker build . --tag ghcr.io/simon-b64/basic-chess:latest

            - name: Push image to registry
              run: docker push ghcr.io/simon-b64/basic-chess --all-tags
